ALTER TYPE "Track" ADD VALUE 'AMMA';
ALTER TYPE "Track" ADD VALUE 'QURAN_GHAIB';
ALTER TYPE "Track" ADD VALUE 'GRADUATED';
ALTER TABLE "Student" ADD COLUMN "promotedAt" TIMESTAMP(3);
ALTER TABLE "Recitation" ADD COLUMN "surahs" TEXT[] DEFAULT ARRAY[]::TEXT[];
